Nathan.figueroa/triton rosinstall
WHOIGit/PhytO-ARM pull request #27
Opened 2023-09-05 17:35 UTC by figuernd

2023-09-06 07:33 UTC, rgov commented
### ⚠️ I force-pushed to fix the authorship information.

Please do a `git fetch && git checkout nathan.figueroa/triton-rosinstall && git reset --hard origin/nathan.figueroa/triton-rosinstall` if you need to work on this locally.

2023-09-06 07:44 UTC, rgov requested changes

2023-09-06 07:44 UTC, rgov commented on configs/example.yaml
> +# If winch = false
This makes it seem like winch and classifier use are mutually exclusive, which they aren't.

2023-09-06 07:44 UTC, rgov commented on Dockerfile
> + && stdbuf -o L catkin build phyto_arm triton_classifier
Shouldn't be needed if `phyto_arm` declares its dependence on `ros-triton-classifier` in the `package.xml` file.

2023-09-06 07:44 UTC, rgov commented on deps/deps.rosinstall
> +    local-name: triton_classifier
Can we make the `local-name` the same as the repo name like the others?

2023-09-06 07:44 UTC, rgov commented on deps/python3-requirements.txt
> +tritonclient[all]==2.33.0
Ideally this would be properly handled by the `ros-triton-classifier` package. Can we just leave a comment to that effect that this is a temporary workaround?

2023-09-06 07:44 UTC, rgov commented on src/ifcb/msg/TriggerContentDaq.msg
> +TBD
Can we delete this file please?

2023-09-06 07:44 UTC, rgov commented on src/ifcb/src/ifcb/node.py
> +        # Convert PNG to raw and publish as Image message
I would prefer that, rather than adding this code here, and the dependencies on OpenCV etc., we run a separate `image_transport` node for doing the conversions:

```
# Convert to roslaunch as needed...
rosrun image_transport republish png in:=/ifcb/roi/image raw out:=/ifcb/roi/image/raw
```

We would want to make sure that the logger node doesn't include the raw messages.

2023-09-12 17:28 UTC, figuernd commented on deps/python3-requirements.txt
> +tritonclient[all]==2.33.0
Done

2023-09-12 17:33 UTC, figuernd commented on src/ifcb/src/ifcb/node.py
> +        # Convert PNG to raw and publish as Image message
Done, factored out into its own node

2023-09-12 17:34 UTC, figuernd commented on src/ifcb/src/ifcb/node.py
> +        # Convert PNG to raw and publish as Image message
When you refer to the logger, do you mean the rosbag record node? It does filter out the appropriate paths if so.

2023-09-15 14:43 UTC, figuernd commented on src/ifcb/src/ifcb/node.py
> +        # Convert PNG to raw and publish as Image message
It appears image_transport requires that the topic is subscribes to have a name that matches the transport type, e.g. /ifcb/roi/image needs to be renamed or remapped to /ifcb/roi/image/compressed in order for the republish node to see the compressed PNGs within.

Since this branch in its current state meets requirements, I would like to merge. I am moving on to other tasks, but we can create an issue for switching to image_transport if needed.

2023-09-15 16:48 UTC, merged

2023-09-15 16:58 UTC, rgov commented
Ok. I squashed the commits and filed #28.

2023-09-15 17:28 UTC, figuernd commented
Thank you!