Major refactor for coordinated multi-winch and testing
WHOIGit/PhytO-ARM pull request #34
Opened 2024-02-29 20:12 UTC by figuernd

This represents a major overhaul which adds a number of new features, including:

1. Support for multiple winches coordinate by a central "lock_manager".
2. Simplified mission programming with an "arm" oriented event-driven architecture.
3. Consolidation of winched and winchless code.
4. Discrete launching for the main nodes and arm nodes. This allows individual arms and their winches to fail or be relaunched with new parameters without disrupting other arm nodes at work.
5. Unit tests for the phyto_arm package. Code coverage is still incomplete but a pattern for testing has been established and ~35 tests written.
6. Development container support, enabling development in an identical environment no matter the development host.
7. Hardware mocking, allowing PhytO-ARM to be run entirely on developer workstations with no need for a development IFCB, motors or CTDs.
8. Config validation for ensuring PhytO-ARM is launched with a config file that meets a simple spec.
9. Multi-camera support.
10. Convenience scripts for ease of starting and stopping in Docker and tmux.

feat: Node and tests for validating configuration

feat: Added launch configuration

fix: config validation nodes executable, validate seatrac

fix: missing shebang

feat: Moved validation from nodes to start script

refactor: Multiple winches WIP. New conductor

refactor: Winch movement

refactor: Instrument actions

feat: Fixed service message locations

feat: Added arm controller for RBR

feat: Node for publishing UDP stream, corrected CTD paths

build: dev container configuration

feat: Multi-camera support

fix: config and build fixes found during testing

feat: Better buffering for RBR stream, service definition for running relay on another device

fix: service import and usage errors

debug: runtime progress

fix: Improved namespace handling, debug logging

fix: Moved instrument specific config to respective arms

fix: Include depth from RBR readings

feat: Misc fixes to paths and parameter passing

feat: Improves task behavior, eliminates race condition

refactor: Use semaphores and events instead of locks

feat: Will run scheduled depth when profile fails to gather enough data

feat: Nomenclature update: Instrument->Payload

feat: Convert state class to dataclass

refactor: reorganized task parameters in yaml

refactor: Move winch control to arm base class

feat: Move IFCB operation out of ARM for easier mocking

feat: Hardware mocking for local development/testing

feat: Upgrade aiohttp

fix: IFCB action call error, improvements to naming, loop locking

feat: Switch from queue to event-driven tasks. Add wiz_probe behavior

test: Unit tests for scheduled depth and wiz behaviors

feat: per-task winch speed, chanos arm using RBR sensor

feat: Removed files from old multiwinch method

fix: Removed unused srv folder/reference

fix: Ensure required version of setuptools is available

feat: Removed unused files/references

feat: Config validation skip switch for launch

feat: Moved mock nodes into their own directory

fix: Misc typos

fix: RBR base behavior fixes

refactor: Arm nodes are now launched independently of core PhytO-ARM nodes

refactor: phyto-arm start now takes a launchfile name arg

fix: Check correct semaphore signal

docs: Comments

doc: Updated documentation

feat: renamed arm launchfiles for consistency

feat: Adjusted chanos config for specific depths

feat: Better exceptions for out of bounds cases in arm base

feat: Added support for wiz probe depth offset config

docs: Better example depths

feat: Switched to named locking mechanism to allow crashed arms to reenter existing locks

feat: Convenience running scripts, fixes missing scripts from build

fix: Misc run script issues

fix: docker image ref

feat: Added development section to README

feat: A little more tolerance for malformed RBR messages

feat: Cleaned up example.yaml

2024-03-01 19:07 UTC, rgov requested changes
This is a partial review. Some simple changes have been put on the rzg/multi-winch-review branch.

I sometimes go a little overboard with rebasing but it is a great way to prepare branches for pull requests by splitting and combining commits into logical changes. Then it would be easier to review different parts of this. It seems like the logical commits would be something like:

1. Add support for dev containers 
2. Add unit testing
3. Add support for the Wiz
4. Add support for multiple winches
5. ...

It seems like there were multiple commits that got merged together into one über-commit. Can we get those back?

2024-03-01 19:19 UTC, figuernd commented
> This is a partial review. Some simple changes have been put on the rzg/multi-winch-review branch.
> 
> I sometimes go a little overboard with rebasing but it is a great way to prepare branches for pull requests by splitting and combining commits into logical changes. Then it would be easier to review different parts of this. It seems like the logical commits would be something like:
> 
>     1. Add support for dev containers
> 
>     2. Add unit testing
> 
>     3. Add support for the Wiz
> 
>     4. Add support for multiple winches
> 
>     5. ...
> 
> 
> It seems like there were multiple commits that got merged together into one über-commit. Can we get those back?

Yeah I thought it would be easier to review the finished product because some detours were taken in the full commit history, but you can see the pre-squashed commits here: https://github.com/WHOIGit/PhytO-ARM/tree/nathan.figueroa/multi-winch-backup

2024-03-05 22:47 UTC, figuernd commented on README.md
> +    docker build --tag whoi-phyto-arm .
Sure I can do that. I think this line was inherited from somewhere else, but I'll change it to match.

2024-03-05 22:50 UTC, figuernd commented on README.md
> +<launchfile name>                 Name of ROS launchfile to use in the phyto_arm package, excluding extension. Currently one of 'main', 'arm_ifcb' or 'arm_chanos'.
They need to be launched independently - operators might want to stop one arm, change something, then relaunch it. Or maybe an arm will crash for some reason that can be fixed and relaunched without interrupting the other launches. This require 3 different launch commands.

Operators also prefer to use a single, unified config file.

2024-03-05 22:56 UTC, figuernd commented on README.md
> +The ROS nodes will be run in the background (so that you can disconnect from the system, for example) within a `screen` session. This session can be attached with the convenience command
Yeah I don't really have an opinion on this. The operators seem to use tmux the most day to day, so I opted for that for familiarity. It's is inconsistent to use both, but probably doesn't hurt to leave this information for anyone who happens to use it natively.

2024-03-05 22:56 UTC, figuernd commented on README.md
> +The `udp_to_ros.py` node is used to read the proxied UDP packets and publish them on a ROS topic to be used by PhytO-ARM.
Oh hmm didn't know there was a UDP option. I'll give it a try.

2024-03-05 23:00 UTC, figuernd commented on README.md
> +      - `ctd_comms/in` for messages received from the CTD's serial port
`ctd_comms` is the node name; no prefix means it's relative to namespace. At the start of the node inventory I have a blurb talking about the prefix meanings.

2024-03-05 23:01 UTC, figuernd commented on configs/example.yaml
> +            # List of times to sample the Wiz probe in UTC time. List can be any size
Done. Config validation should also catch that.

2024-03-05 23:03 UTC, figuernd commented on deps/apt-requirements.txt
> +netcat
Debugging. I often found myself having to install it in the container so that I could verify some network traffic was behaving as expected.

2024-03-05 23:04 UTC, figuernd commented on phyto-arm
> +    if args.launch_name == "main":
I wanted to make sure it was the only one launching roscore, but I shouldn't have alerts and logging in there too, will reduce that scope.

2024-03-05 23:05 UTC, figuernd commented on scripts/__init__.py
It is; the unit tests can't import from `config_validation.py` otherwise.

2024-03-05 23:08 UTC, figuernd commented on scripts/config_validation.py
> +    return annotations
Yeah I had to come up with a custom parser to be able to act on comments. A more robust solution would be a proper YAML schema using maybe Rx or JSON-schema extensions, but this has been pretty robust so far and should save a lot of headaches in deployment.

2024-03-05 23:09 UTC, figuernd commented on src/phyto_arm/src/arm_ifcb.py
> +            return Task("wiz_probe", lambda _: await_wiz_probe(self.start_next_task, wiz_depth))
Good catch, this was a bug I ran into last night.

2024-03-05 23:10 UTC, figuernd commented on src/phyto_arm/src/arm_ifcb.py
> +        return rospy.get_param('tasks/wiz_probe/default_depth')
I see what you mean. I'll refactor.

2024-03-05 23:10 UTC, figuernd commented on src/phyto_arm/src/arm_ifcb.py
> +        raise
Sure doesn't look like it; will remove.

2024-03-06 20:10 UTC, figuernd commented on README.md
> +The `udp_to_ros.py` node is used to read the proxied UDP packets and publish them on a ROS topic to be used by PhytO-ARM.
Okay tried this: Not sure what the bridge is doing, but it seems to be splitting the messages at strange points. 

Messages should be newline delimited, here is a sample from the RBR:
```
2024-03-06 20:05:00.750, 29.2280, 5.1300, 10.9558, 4.1566, 0.0305, 5.1897, 435.8503, 5.7348, 226.5525, 0.8233, 0.8166, 30.0221, 1464.9415, 47105.2640, 133.7677
2024-03-06 20:05:00.875, 29.2287, 5.1253, 10.9554, 3.4164, 0.0270, 5.1897, 435.8324, 5.9243, 227.0349, 0.8229, 0.8162, 30.0272, 1464.9287, 47113.2680, 133.7515
2024-03-06 20:05:01.000, 29.2297, 5.1254, 10.9560, 2.6810, 0.0279, 5.1897, 435.8294, 5.8173, 227.7548, 0.8235, 0.8168, 30.0282, 1464.9304, 47114.7320, 133.7518
2024-03-06 20:05:01.125, 29.2274, 5.1261, 10.9558, 1.9898, 0.0388, 5.1897, 435.8397, 5.9843, 228.6714, 0.8233, 0.8166, 30.0248, 1464.9294, 47109.7920, 133.7545
```

But I got a lot of malformed message errors:
```
[WARN] [1709755477.982240]: Discarding malformed RBR message - expected 16 fields but received 11
[WARN] [1709755478.080177]: Discarding malformed RBR message - expected 16 fields but received 5
[WARN] [1709755478.108332]: Discarding malformed RBR message - expected 16 fields but received 12
[WARN] [1709755478.203447]: Discarding malformed RBR message - expected 16 fields but received 6
[WARN] [1709755478.233029]: Discarding malformed RBR message - expected 16 fields but received 11
[WARN] [1709755478.332212]: Discarding malformed RBR message - expected 16 fields but received 6
[WARN] [1709755478.359101]: Discarding malformed RBR message - expected 16 fields but received 11
[WARN] [1709755478.456724]: Discarding malformed RBR message - expected 16 fields but received 5
```

Not all were malformed - enough made it through that the RBR was still moving, but a significant chunk produced these errors. My custom relay seems more robust, so I'm going to stick with that unless some solution presents itself.

2024-03-06 20:19 UTC, rgov commented on README.md
> +The `udp_to_ros.py` node is used to read the proxied UDP packets and publish them on a ROS topic to be used by PhytO-ARM.
Can you get a tcpdump of these UDP packets? Are there full lines in each packet or are they fragmented? Is this from a Moxa and if so is it (can it be) configured to line buffer?

DSL heavily uses UDP packets and I'm sure many of them are newline-delimited so I am sure it works in the right configuration. 

Stefano Suman and Ian Vaughn wrote it and can advise.

2024-03-12 17:08 UTC, figuernd commented on README.md
> +The `udp_to_ros.py` node is used to read the proxied UDP packets and publish them on a ROS topic to be used by PhytO-ARM.
No longer have development hardware setup to debug this, I've created a redmine task to track this and will plan on trying again in a future version.

2024-03-12 19:34 UTC, figuernd commented
I've gone through with pylint and applied most suggestions. I do have the following configurations applied however:
```
--disable=missing-function-docstring, missing-class-docstring, missing-module-docstring, global-statement, unused-argument, import-error, invalid-name, unnecessary-lambda-assignment
--max-line-length=120
```

I've also ensured a blank line before most comments, with the exception of inline comments and comments immediately following a function heading or if statement.

2024-03-18 19:44 UTC, rgov requested changes

2024-03-18 19:44 UTC, rgov commented on phyto-arm
> +        roscore = subprocess.Popen('roscore', env=env)
The `roscore` variable is used unconditionally when shutting down the nodes (line 174ish), but now it is only defined when `launch_name == "main"`.

2024-05-13 21:18 UTC, figuernd commented on phyto-arm
> +        roscore = subprocess.Popen('roscore', env=env)
Good eye, I think I ran into this throwing errors before I saw your note and fixed here https://github.com/WHOIGit/PhytO-ARM/commit/60b3bd081af0f0fd78b0fcd4bbcfda418c73ea92

2024-05-14 19:17 UTC, figuernd commented on README.md
> +<launchfile name>                 Name of ROS launchfile to use in the phyto_arm package, excluding extension. Currently one of 'main', 'arm_ifcb' or 'arm_chanos'.
Fixed line wrapping in c180df03de7fabc78f89a11c557621e4e9572904

2024-05-14 19:21 UTC, figuernd commented on README.md
> +The ROS nodes will be run in the background (so that you can disconnect from the system, for example) within a `screen` session. This session can be attached with the convenience command
Went ahead an removed references to screen in f6907ac48bd9daa1409638cbb92113cedcd362ce

2024-05-14 20:02 UTC, figuernd commented on src/phyto_arm/src/arm_base.py
> +                rospy.logerr(f"Unexpected error: {e}")
Neat, tested and confirmed it works. 99657a3ed106ccde6eb65c7fd404e3519adcc456

2024-05-14 22:54 UTC, rgov commented
I'd say rebase and merge if this is tested.

2024-05-16 15:45 UTC, merged

2025-06-02 06:36 UTC, rgov commented
Do you remember why this installs `setuptools==69.1.0`?