John.walsh/digital logger
WHOIGit/PhytO-ARM pull request #49
Opened 2024-10-08 22:12 UTC by johnwaalsh

Adds the digital logger node. The digital logger node will publish the statuses of each outlet as a separate topic in the form `/digital_logger/outlets/{outlet num}/status`. To change the status of an outlet, publish to the control service `/digital_logger/control` specifying an outlet name and a status ("on" or "off"). The OutletStatus message type is added to contain this information.

2024-10-11 20:59 UTC, figuernd commented on configs/example.yaml
> +    password: "1234"
We have a tradition of storing these types of passwords in the YAML since it all runs locally but I wonder if we should consider a more robust secret store

2024-10-11 21:28 UTC, figuernd requested changes

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +from requests.auth import HTTPDigestAuth
We try to follow this convention for import order: https://peps.python.org/pep-0008/#imports

In particular:
```
Imports should be grouped in the following order:

    Standard library imports.
    Related third party imports.
    Local application/library specific imports.

You should put a blank line between each group of imports.
```

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +    username = rospy.get_param('/digital_logger/username')
Prefer relative parameters (e.g. `~username`) because it allows the node namespace to change if a launchfile gets refactored without breaking the code

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +        response = requests.get(f'http://{username}:{password}@{address}/restapi/relay/outlets/=0,1,2,3,4,5,6,7/state/')
Looks like this assumes 8 outlets; is that always the case?

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +        result = json.loads(response.text)
If a digital logger is not on the network, will this crash? I don't see a way to disable this node from the config YAML. We might want to only launch this node if that config section is present, we try not to make the operators touch the launch files if possible.

2024-10-11 21:28 UTC, figuernd commented on configs/example.yaml
> +digital_logger:
Should probably add #optional to this section since digital loggers aren't always used

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +        outlet_publishers[f'outlet_{outlet_num}'] = rospy.Publisher(f'/digital_logger/outlet/{outlet_num}/status/', OutletStatus, queue_size=10)
Why bother with `f'outlet_{outlet_num}'`? If index is the key anyway, why not just append them to a list?

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +    rospy.loginfo(f'sent: http://{address}/restapi/relay/outlets/{outlet_num}/state/, auth={username},{password} status={str(status).lower()}, received: code {response.status_code} : {response.text}'
Nitpick: Redundant string construction

Also, let's not log the password, (I know it's not a secure password at all to begin with, just as a best practice so that we have one less hole to fix if we do move to secret stores)

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +            # outlet numbers in the config yaml start from 1 whereas outlet numbers in the API start from 0
This is fine, but it would also be fine just to require the YAML start at 0

2024-10-11 21:28 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +    subscriber = rospy.Subscriber('/digital_logger/control', OutletStatus, control_outlet)
I think subscriber here isn't used, right? If you haven't already, install PyLint, it should catch this kind of thing

2024-10-11 21:29 UTC, figuernd commented on configs/example.yaml
> +    password: "1234"
This isn't a request for change, just commenting for discussion. @rgov is out right now but may have thought about this.

2024-11-22 19:55 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +from requests.auth import HTTPDigestAuth
Updated the imports in [61844cb](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/61844cb8a84b0af18b28c70a6b03d5ad58611568) to follow PEP 8

2024-11-22 19:57 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +    username = rospy.get_param('/digital_logger/username')
Switched to relative parameters in [f762939](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/f7629398c6ef69c50197314d2f5c8f2f16f6cae6).

2024-11-22 19:59 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +        response = requests.get(f'http://{username}:{password}@{address}/restapi/relay/outlets/=0,1,2,3,4,5,6,7/state/')
For the digital logger I have, it's always 8, but I think flexibility is good if we end up using other digital loggers. Updated this to use the number of outlets specified in the config file in [4bcd656](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/4bcd6567147696ba735870451ac844910cf0736f).

2024-11-22 20:01 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +        result = json.loads(response.text)
Updated the config yaml to have a parameter for specifying if the digital logger will be used in [85908a4](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/85908a47514f0a275c666287a63ff67966e3abba).

2024-11-22 20:02 UTC, rgov commented on src/phyto_arm/src/digital_logger_node.py
> +import requests
We don't currently use `requests`. Could you please convert to `urllib` or `httplib` in the standard library?

If the device supports Basic HTTP authentication, you can just set the header `Authorization: Basic {base64.b64encode(f"{user}:{password}")}`. If not, there's a more convoluted way to do it with `urllib.request.HTTPDigestAuthHandler`

2024-11-22 20:02 UTC, johnwaalsh commented on configs/example.yaml
> +digital_logger:
Added optional comment in [da0474b](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/da0474bcdd03922025204eb3aefa1a3082e3207f).

2024-11-22 20:04 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +        outlet_publishers[f'outlet_{outlet_num}'] = rospy.Publisher(f'/digital_logger/outlet/{outlet_num}/status/', OutletStatus, queue_size=10)
Good call, simplified this to just use a list in [6b62bc3](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/6b62bc3b2c85b4007d37b8f706ae101e91b30325).

2024-11-22 20:06 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +    rospy.loginfo(f'sent: http://{address}/restapi/relay/outlets/{outlet_num}/state/, auth={username},{password} status={str(status).lower()}, received: code {response.status_code} : {response.text}'
Fixed the redundant string conversion and removed the auth from the log in [0334c5f](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/0334c5ff3db3867aa84154c8a59b7cd1dd27dc53).

2024-11-22 20:16 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +            # outlet numbers in the config yaml start from 1 whereas outlet numbers in the API start from 0
Yeah, I agree that it's best to have everything start at 0. I switched the yaml to start at 0 in [7024a3d](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/7024a3de841dbd8e1cc0744139c3989b9bc7074d) and [bbd2efd](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/bbd2efde1db701ab36ea7399426d5aa4ff1cead9). The digital logger default outlet names start at 1 (names displayed on the device), so there may be a bit of a disconnect there for users. I wonder if we should have the names from the yaml automatically change the names on the device when run, to prevent this confusion (e.g., have an outlet on the device appear as "ifcb" instead of "outlet 5").

2024-11-26 23:46 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +import requests
Ok, updated this to use http.client in [7e2094a](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/7e2094a01060fc0c4e1cffa043a76dda5eaa60b0). I shifted the code to a class structure so the HTTP connections (one for status checking, and one for changing the logger) persist over multiple requests.

2024-11-27 00:12 UTC, rgov requested changes

2024-11-27 00:12 UTC, rgov commented on src/phyto_arm/src/digital_logger_node.py
> +                # DL API uses 'true' and 'false' to denote outlet status, which need to be converted to Python bools
Could you explain your preference for the strings `on` and `off` versus using a boolean here? If there's more than two states, we should use an "enum" (in ROS that's just a set of constants like `OUTLET_STATUS_OFF = 0`).

```python
status = (outlet_result.lower() == 'true')
```

2024-11-27 00:12 UTC, rgov commented on src/phyto_arm/src/digital_logger_node.py
> +        digital_logger = DigitalLogger()
I actually like it better not using a separate class. I have been meaning to write a blog post on this, but in brief:

- Classes provide encapsulation so you can have multiple instances of something.
- If you want multiple loggers, you can already just spawn multiple nodes. Nodes are run as separate processes, which are encapsulated in their own virtual memory space / execution context already.
- Only one instance of the `DigitalLogger` class is being created anyway. This class is tightly bound to the ROS node API. If it were architected so that `DigitalLogger` could be used outside of the ROS ecosystem, it would be more justifiable.
- The complexity of wrapping everything in a class is not free; the code gets more verbose with an extra level of indentation and `self` everywhere.

2024-11-27 19:38 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +                # DL API uses 'true' and 'false' to denote outlet status, which need to be converted to Python bools
Yeah we should ensure 'true' and 'false' are the only possible responses; perhaps there's an unknown?

Using a boolean would require changing the message property name to something like `OutletStatus.is_active`, which might be more appropriate anyway if you think of the status as being the entire message on not just the power.

2024-11-27 19:40 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +        digital_logger = DigitalLogger()
Good point, we seldom use classes for nodes; usually only for data objects or sometimes inheritance.

@johnwaalsh an example of a classless node: https://github.com/WHOIGit/PhytO-ARM/blob/main/src/phyto_arm/src/winch_node.py

2025-01-02 16:27 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +                # DL API uses 'true' and 'false' to denote outlet status, which need to be converted to Python bools
There are only two states an outlet status can have: true or false. My thought was that "on" and "off" would be more explicit than using "true" or "false" to represent status. Although I agree that using a boolean `is_active` variable is clearer, I updated the message type to use a boolean instead.

2025-01-02 16:29 UTC, johnwaalsh commented on src/phyto_arm/src/digital_logger_node.py
> +        digital_logger = DigitalLogger()
Yeah, that makes sense to me, especially since there's realistically only one digital logger node being created. I switched this to a classless structure in [ebde1dd](https://github.com/WHOIGit/PhytO-ARM/pull/49/commits/ebde1dd36056f66d255db3fe3828e353337c9717).

2025-01-02 18:29 UTC, figuernd commented on src/phyto_arm/src/digital_logger_node.py
> +            # outlet numbers in the config yaml start from 1 whereas outlet numbers in the API start from 0
Ah I see, the API does not line up with the names, so the YAML has to be one or the other. We can just ask that we name outlets from 0 going forward as a convention for anyone setting up a DL.

2025-01-02 18:30 UTC, figuernd approved these changes
Thanks for making these changes.

2025-01-02 19:29 UTC, merged

2025-01-07 20:49 UTC, rgov commented
Nice to see this get in. Can we coordinate re-applying this as a squash so we don't have all the intermediate commits in history? We can do it this week.